/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package storemanagementsystem;

import javax.swing.JOptionPane;
/**
 *
 * @author Asus
 */
public class StoreTransactionFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StoreTransactionFrame.class.getName());

    /**
     * Creates new form StoreTransactionFrame
     */
    public StoreTransactionFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        // Populate ComboBox using the array from the main class
        ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(StoreManagementSystem.itemNames));
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Product = new javax.swing.JLabel();
        Quantity = new javax.swing.JLabel();
        ComboBox = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        Order = new javax.swing.JButton();
        Logs = new javax.swing.JButton();
        Inventory = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Product.setText("products");

        Quantity.setText("quantity");

        ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rice", "Sugar ", "Coffee", "Milk" }));

        Order.setText("Order");
        Order.addActionListener(this::OrderActionPerformed);

        Logs.setText("Logs");
        Logs.addActionListener(this::LogsActionPerformed);

        Inventory.setText("Inventory");
        Inventory.addActionListener(this::InventoryActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Product, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(Order)))
                .addContainerGap(75, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(Logs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Inventory)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Product, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(Order)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Logs)
                    .addComponent(Inventory))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderActionPerformed
        // TODO add your handling code here:
        try {
            int selectedIndex = ComboBox.getSelectedIndex();
            String qtyString = jTextField1.getText();

            // 1. Validation Checks
            if (qtyString.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter a quantity.", "Input Error", JOptionPane.WARNING_MESSAGE);
                return;
            }

            int qty = Integer.parseInt(qtyString);

            if (qty <= 0) {
                JOptionPane.showMessageDialog(this, "Quantity must be greater than 0!", "Invalid Quantity", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // 2. Check against shared inventory array
            if (qty > StoreManagementSystem.stockLevels[selectedIndex]) {
                JOptionPane.showMessageDialog(this, "Insufficient stock! Only " + StoreManagementSystem.stockLevels[selectedIndex] + " units left.", "Stock Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // 3. Process Transaction computations
            double price = StoreManagementSystem.itemPrices[selectedIndex];
            double totalCost = price * qty;

            // 4. Deduct from inventory array
            StoreManagementSystem.stockLevels[selectedIndex] -= qty;

            // 5. Save to transaction log arrays
            if (StoreManagementSystem.totalTransactions < StoreManagementSystem.LOG_LIMIT) {
                int logIdx = StoreManagementSystem.totalTransactions;
                StoreManagementSystem.logItems[logIdx] = StoreManagementSystem.itemNames[selectedIndex];
                StoreManagementSystem.logQuantities[logIdx] = qty;
                StoreManagementSystem.logSubtotals[logIdx] = totalCost;
                StoreManagementSystem.totalTransactions++; 
            }

            // 6. Show Receipt
            String receipt = "=== TRANSACTION SUCCESSFUL ===\n\n" +
                             "Item: " + StoreManagementSystem.itemNames[selectedIndex] + "\n" +
                             "Quantity: " + qty + "\n" +
                             "Total Paid: ₱" + totalCost;
            
            JOptionPane.showMessageDialog(this, receipt, "Order Complete", JOptionPane.INFORMATION_MESSAGE);

            // 7. Reset text field for the next customer
            jTextField1.setText(""); 

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid whole number.", "Input Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_OrderActionPerformed

    private void LogsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogsActionPerformed
        // TODO add your handling code hezre:
        new TransactionLogsFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogsActionPerformed

    private void InventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InventoryActionPerformed
        // TODO add your handling code here:
        new InventoryFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_InventoryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new StoreTransactionFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBox;
    private javax.swing.JButton Inventory;
    private javax.swing.JButton Logs;
    private javax.swing.JButton Order;
    private javax.swing.JLabel Product;
    private javax.swing.JLabel Quantity;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
